server:
  port: ${sms.user_service.port}
eureka:
  client:
    serviceUrl:
      defaultZone: ${sms.eureka.defaultZone}

---
eureka:
  instance:
    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 80
spring:
  profiles: cloud
  jmx:
    enabled: false
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    password: ${sms.user_service.postgre.password}
    username: ${sms.user_service.postgre.username}
    url: ${sms.user_service.postgre.url}
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true