server:
  port: ${sms.service.user.port}

eureka:
  instance:
    hostname: ${APPLICATION_DOMAIN}
  client:
    serviceUrl:
      defaultZone: ${sms.eureka.defaultZone}

spring:
  jmx:
    enabled: false
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    password: ${sms.service.user.postgre.password}
    username: ${sms.service.user.postgre.username}
    url: ${sms.service.user.postgre.url}
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true