server:
  port: 8762
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceUrl:
    defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/

zuul:
  routes:
    usersService:
      path: /users-service/**
      serviceId: USERS-SERVICE
    ordersService:
      path: /orders-service/**
      serviceId: ORDERS-SERVICE