server:
  port: ${saar.zuul_service.port}
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceUrl:
    defaultZone: ${saar.eureka.defaultZone}

zuul:
  routes:
    usersService:
      path: /users-service/**
      serviceId: ${saar.user_service.service.name}
    ordersService:
      path: /orders-service/**
      serviceId: ${saar.orders_service.service.name}