server:
  port: ${sms.orders_service.port}
spring:
  profiles: cloud
  data:
    mongodb.uri: ${sms.orders_service.mongodb.uri}
eureka:
  client:
    serviceUrl:
      defaultZone: ${sms.eureka.defaultZone}
  instance:
    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 80